name: Release
run-name: Release ${{ inputs.APP_VERSION }}${{ inputs.TAG_SUFFIX }}

on:
  workflow_dispatch:
    inputs:
      APP_VERSION:
        description: 'ExpressVPN App Version'
        required: true
        default: '3.83.0.2-1'
      TAG_SUFFIX:
        description: 'Tag suffix (used when patching existing versions)'
        required: false
        default: ''
      LATEST:
        description: 'Whether it should be tagged as latest'
        required: false
        default: 'true'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and Push version
      run: docker buildx build --build-arg APP_VERSION=${{ inputs.APP_VERSION }} --platform=linux/i386,linux/amd64,linux/arm64,linux/armhf -t dizgovin/expressvpn:${{ inputs.APP_VERSION }}${{ inputs.TAG_SUFFIX }} --push .
    - name: Build and Push latest
      if: ${{ inputs.LATEST == 'true' }}
      run: docker buildx build --build-arg APP_VERSION=${{ inputs.APP_VERSION }} --platform=linux/i386,linux/amd64,linux/arm64,linux/armhf -t dizgovin/expressvpn:latest --push .
